export const APARTMENTS = [
  {
    id: 1,
    name: "Perth CBD Apartments for Rent",
    neighbourhood: "Perth CBD",
    type: "Various",
    listingType: "rent",
    rentPrice: "From $1,800/month",
    buyPrice: "From $450,000",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80",
    features: ["City Views", "Pool", "Gym", "Parking"],
    description: "Browse all available rental apartments in Perth CBD on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/rental-properties/perth/apartments/"
  },
  {
    id: 2,
    name: "Perth CBD Apartments for Sale",
    neighbourhood: "Perth CBD",
    type: "Various",
    listingType: "buy",
    rentPrice: "From $1,800/month",
    buyPrice: "From $450,000",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
    features: ["Waterfront Views", "Concierge", "Pool", "Gym"],
    description: "Browse all apartments for sale in Perth CBD on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/for-sale/perth/apartments/"
  },
  {
    id: 3,
    name: "Northbridge Apartments for Rent",
    neighbourhood: "Northbridge",
    type: "Various",
    listingType: "rent",
    rentPrice: "From $1,600/month",
    buyPrice: "From $380,000",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80",
    features: ["Rooftop Terrace", "WiFi", "Near Restaurants", "Modern Kitchen"],
    description: "Browse all available rental apartments in Northbridge on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/rental-properties/northbridge/apartments/"
  },
  {
    id: 4,
    name: "Northbridge Apartments for Sale",
    neighbourhood: "Northbridge",
    type: "Various",
    listingType: "buy",
    rentPrice: "From $1,600/month",
    buyPrice: "From $380,000",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&q=80",
    features: ["High Ceilings", "Exposed Brick", "Trendy Area", "Bike Storage"],
    description: "Browse all apartments for sale in Northbridge on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/for-sale/northbridge/apartments/"
  },
  {
    id: 5,
    name: "Subiaco Apartments for Rent",
    neighbourhood: "Subiaco",
    type: "Various",
    listingType: "rent",
    rentPrice: "From $1,700/month",
    buyPrice: "From $400,000",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
    features: ["Garden Views", "Pet Friendly", "Quiet Street", "Near Shops"],
    description: "Browse all available rental apartments in Subiaco on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/rental-properties/subiaco/apartments/"
  },
  {
    id: 6,
    name: "Subiaco Apartments for Sale",
    neighbourhood: "Subiaco",
    type: "Various",
    listingType: "buy",
    rentPrice: "From $1,700/month",
    buyPrice: "From $400,000",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=600&q=80",
    features: ["Cafe Strip", "Boutique Shops", "Sunny Aspect", "Modern Kitchen"],
    description: "Browse all apartments for sale in Subiaco on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/for-sale/subiaco/apartments/"
  },
  {
    id: 7,
    name: "Scarborough Apartments for Rent",
    neighbourhood: "Scarborough",
    type: "Various",
    listingType: "rent",
    rentPrice: "From $2,000/month",
    buyPrice: "From $500,000",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=600&q=80",
    features: ["Ocean Views", "Beach Access", "Pool", "Balcony"],
    description: "Browse all available rental apartments in Scarborough on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/rental-properties/scarborough/apartments/"
  },
  {
    id: 8,
    name: "Scarborough Apartments for Sale",
    neighbourhood: "Scarborough",
    type: "Various",
    listingType: "buy",
    rentPrice: "From $2,000/month",
    buyPrice: "From $500,000",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80",
    features: ["Panoramic Ocean Views", "Rooftop Pool", "Gym", "Concierge"],
    description: "Browse all apartments for sale in Scarborough on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/for-sale/scarborough/apartments/"
  },
  {
    id: 9,
    name: "Fremantle Apartments for Rent",
    neighbourhood: "Fremantle",
    type: "Various",
    listingType: "rent",
    rentPrice: "From $1,600/month",
    buyPrice: "From $380,000",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80",
    features: ["Heritage Building", "Port Views", "Near Markets", "Parking"],
    description: "Browse all available rental apartments in Fremantle on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/rental-properties/fremantle/apartments/"
  },
  {
    id: 10,
    name: "Fremantle Apartments for Sale",
    neighbourhood: "Fremantle",
    type: "Various",
    listingType: "buy",
    rentPrice: "From $1,600/month",
    buyPrice: "From $380,000",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=600&q=80",
    features: ["Port Views", "Luxury Finishes", "Wine Cellar", "Double Garage"],
    description: "Browse all apartments for sale in Fremantle on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/for-sale/fremantle/apartments/"
  },
  {
    id: 11,
    name: "South Perth Apartments for Rent",
    neighbourhood: "South Perth",
    type: "Various",
    listingType: "rent",
    rentPrice: "From $2,200/month",
    buyPrice: "From $550,000",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=600&q=80",
    features: ["City Skyline Views", "Near Perth Zoo", "Cycle Path", "Ferry Access"],
    description: "Browse all available rental apartments in South Perth on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/rental-properties/south-perth/apartments/"
  },
  {
    id: 12,
    name: "South Perth Apartments for Sale",
    neighbourhood: "South Perth",
    type: "Various",
    listingType: "buy",
    rentPrice: "From $2,200/month",
    buyPrice: "From $550,000",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=600&q=80",
    features: ["Penthouse", "360 Views", "Private Rooftop", "Smart Home"],
    description: "Browse all apartments for sale in South Perth on reiwa.com.au.",
    bookingLink: "https://reiwa.com.au/for-sale/south-perth/apartments/"
  },
]

export const NEIGHBOURHOODS = [
  { slug: "perth-cbd", name: "Perth CBD", description: "The vibrant heart of Perth with world-class dining, shopping and entertainment.", icon: "🏙️", highlights: ["Elizabeth Quay", "Hay Street Mall", "Cultural Centre", "Kings Park"] },
  { slug: "northbridge", name: "Northbridge", description: "Perth's cultural and entertainment hub, packed with restaurants, bars and galleries.", icon: "🎨", highlights: ["Perth Cultural Centre", "WA Museum", "Restaurant Strip", "Nightlife"] },
  { slug: "subiaco", name: "Subiaco", description: "A leafy, upmarket suburb with boutique shops, cafes and excellent transport links.", icon: "🌿", highlights: ["Rokeby Road", "Subiaco Oval", "Farmers Market", "Cafes"] },
  { slug: "scarborough", name: "Scarborough", description: "A stunning beachside suburb with one of Perth's most popular beaches.", icon: "🏖️", highlights: ["Scarborough Beach", "Esplanade", "Surf Club", "Beach Volleyball"] },
  { slug: "fremantle", name: "Fremantle", description: "A historic port city with bohemian culture, amazing markets and craft beer.", icon: "⚓", highlights: ["Fremantle Markets", "Fishing Boat Harbour", "Little Creatures", "Prison Tour"] },
  { slug: "south-perth", name: "South Perth", description: "A prestigious riverside suburb with stunning city skyline views.", icon: "🌅", highlights: ["Swan River", "Perth Zoo", "Mend Street Jetty", "Cycle Paths"] },
]
